tryber/sd-010-b-project-frontend-online-store

- package-lock.json
- src/App.js
adicionando um espaço em branco no App.js
>  Testando o Funcionamento da Branch

- package-lock.json
- src/services/api.js
> [Grupo 19] [Requisição da API]

- package-lock.json
- src/App.js
> teste-lucas

- package-lock.json
- src/App.js
- src/services/api.js
> [REQ1][GETAPI]

- package-lock.json
- src/App.js
- src/services/api.js
Requisito 1 finalizado, favor fazer o review :)
> Grupo 10/req 01

- src/App.js
- src/components/Homepage.jsx
Componente Homepage criado, favor fazer o CR
> Criado componente Homepage e adicionado rotas no component App

- package-lock.json
- src/services/api.js
> first requirement, API requisitions

- README.md
- src/App.js
- src/components/Home.jsx
- src/services/api.js
> Group 19 requisito 02

- package-lock.json
- src/services/api.js
> [Grupo 2] [Online Store]

- package-lock.json
- src/App.js
- src/services/api.js
> Grupo-11-Requisito 1-Completo

- package-lock.json
- src/App.js
- src/services/api.js
Primeiro requisito sendo montado pela equipe 12
> [Group-12][Project Frontend Online Store]

- src/App.js
- src/component/Home.js
- src/component/ShoppingCart.js
> [GRUPO 7][REQ 3]

- package-lock.json
- src/App.js
- src/components/Homepage.jsx
- src/components/PageCart.jsx
Requisito 10 finalizado, façam o review, please! :)
> [Grupo 10] [Requisito 03]

- src/App.js
- src/components/Input.jsx
> Main group 2 req 2

- src/App.js
> Grupo 3 - Requisito 2

- package-lock.json
- package.json
- src/App.js
- src/components/Home.jsx
- src/components/ShoppingCart.jsx
> [Group 19 ] [requisito 03]

- src/App.js
- src/components/Categories.css
- src/components/Categories.jsx
> [Group 19] Requisito - 04

- src/App.js
- src/components/ShoppingCart.js
Requisito 3 foi feito na branch do requisito 1 por falta  de atenção. Mas é o requisito 3, e está passando localmente.
> Group-9 [Req3 implementation]

- src/App.js
- src/components/InputSearch.jsx
- src/services/api.js
> [Main group 22][requisito 5 - listagem de produtos]

- src/components/Categories.jsx
- src/pages/Home.jsx
Gente, pro requisito 4 eu criei uma nova pasta chamada components e dentro dela criei um componente chamado Categories que renderiza as categorias obtidas através do fetch que fizemos no requisito 1. Além disso importei ele e renderizei o mesmo no componente Home
> [GRUPO 6] [REQUISITO 4]

- src/component/CategoryList.js
- src/component/Home.js
> [GRUPO 7][REQ 4]

- src/App.js
- src/components/Homepage.jsx
- src/components/productsByTerms.jsx
> [GRUPO 10] requisito 5

- src/App.js
- src/pages/Home.jsx
- src/services/api.js
> Group 11 requisito 2

- src/App.js
- src/components/Header.jsx
- src/components/ShoppingCart.jsx
- src/index.js
- Configurado BrowserRoute
- Rotas configuradas
> [Grupo 17 ] Main group 17 req 3

- src/components/CatList.js
- src/pages/Home.js
Requirement 4th - create category list at home page.
> [Requisito 4] [Grupo 4]

- src/App.js
- src/components/CartButton.jsx
- src/components/Input.jsx
- src/pages/Cart.jsx
> Main group 2 req 3

- src/App.js
- src/components/CategoryList.jsx
> [Grupo 12] Requisito 04

- src/components/Categories.jsx
- src/pages/Home.jsx
- src/services/api.js
> [Main-group-22][requisito 6]

- package-lock.json
- src/App.js
- src/components/CategoryList.jsx
- src/components/Homepage.jsx
- src/components/productsByTerms.jsx
> [GRUPO 10] Requisito 6 de novo. 

- src/components/Categories.jsx
- src/components/Home.jsx
- src/components/ProductList.jsx
- src/services/api.js
> [Grupo 19] - Requisito 05

- package-lock.json
- src/components/ListCategories.jsx
- src/components/pages/Home.jsx
- src/services/api.js
[X] - Cria component ListCategories que renderiza a lista de categorias na Home.
> [Grupo 14] [Requisito 4]

- src/App.css
- src/App.js
- src/components/Header.jsx
- src/components/Input.jsx
- src/pages/Home.jsx
> Adicionando um estilo e css em nossa pagina

- src/App.css
- src/components/CategoryList.jsx
- src/components/Header.jsx
- src/components/Main.jsx
- src/components/ProductCard.jsx
> [Grupo 12] Requisito 5

- src/components/CategoryList.jsx
- src/components/Main.jsx
>  [Main Group 12 ] Req 6

- README.md
- package-lock.json
- src/App.js
- src/components/List.js
> [add: implements research input; modified file: app.js / list.js]

- src/App.js
- src/components/ListCategories.jsx
- src/components/Loading.jsx
- src/components/ProductsSearchBar.jsx
- src/pages/ShoppingHome.jsx
> [grupo 21] Main group 21 item 4

- src/components/Input.jsx
- src/components/ProductCard.jsx
- src/components/ProductsList.jsx
- src/pages/Home.jsx
- src/services/api.js
Fazendo requisição à API do Mercado Livre através do filtro determinado pelo valor do input da Home Page
> Adiciona funções onChange e onClick para o input e para o botão

- src/pages/Cart.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
> [main-group-22] [requisito 10]

- src/App.css
- src/App.js
- src/components/Main.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetails.jsx
> [Grupo 12] Requisito 07

- src/App.css
- src/App.js
- src/components/Main.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetails.jsx
- src/components/ShopCart.jsx
> [Grupo 12] Requisito 08

- src/App.css
- src/App.js
- src/components/Main.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetails.jsx
- src/components/ShopCart.jsx
> [Grupo 12] Requisito 09

- src/components/Input.jsx
- src/components/ProductCard.jsx
- src/components/ProductsList.jsx
- src/pages/Home.jsx
> Main group 11 requisito 5

- src/App.js
- src/components/Category.jsx
- src/components/ListCategory.jsx
- src/components/index.jsx
- src/index.js
- Criado componente Category
- Criado componente ListCategory
> Main group 17 req 4

- src/components/ListProducts.jsx
- src/components/SearchBox.jsx
- src/components/pages/Home.jsx
> Requisito 05 completo version 1.0

- src/App.js
- src/components/Categories.jsx
- src/components/Header.jsx
- src/components/Home.jsx
- src/components/ProductDetails.jsx
- src/components/ProductList.jsx
- src/services/api.js
> [Group 19] [header component]

- src/__tests__/requirement05.test.js
- src/__tests__/requirement06.test.js
- src/__tests__/requirement07.test.js
- src/__tests__/requirement08.test.js
- src/__tests__/requirement09.test.js
- src/__tests__/requirement10.test.js
- src/__tests__/requirement11.test.js
- src/__tests__/requirement12.test.js
- src/__tests__/requirement13.test.js
- src/__tests__/requirement14.test.js
- src/__tests__/requirement15.test.js
- src/components/CategoryList.jsx
- src/pages/Index.jsx
> [GRUPO 8][REQUISITO 04]

- src/components/Home.jsx
- src/components/NavBar.jsx
> Main group 15 correcao bug

- src/App.js
- src/components/CategoryList.js
> Req4 implementation

- src/App.js
- src/components/CategoryList.js
- src/components/Home.js
- src/components/ProductList.js
- src/components/SearchBar.js
> [Main group 7][req 6]

- src/App.js
- src/components/Input.jsx
- src/components/Loading.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
> Main group 2 req 05

- public/index.html
- src/App.css
- src/components/Form.jsx
- src/components/ProductDetails.jsx
Colegas, feito requisito 11 por mim, Carlos e Aderson. #vqv
> [Group 12] Requisito 11

- src/components/SearchBar.jsx
- src/components/SearchButton.jsx
- src/components/SearchList.jsx
- src/services/api.js
> inicio req 05

- src/components/ListCategories.jsx
- src/components/ListProducts.jsx
- src/components/SearchBox.jsx
- src/components/pages/Home.jsx
- src/services/api.js
> [Grupo 14] [Requisito 6]

- src/components/Rating.jsx
- src/pages/ProductDetails.jsx
> [ GRUPO 17 ] [ Requirement 11 - Creates a rating field on detail page ]

- src/pages/Home.jsx
- src/services/api.js
Realizei as chamadas das APIs.
Programa roda como esperado, porém não passa nos testes.
[Requisito 06] - Ainda incompleto
> [Group 19] Get API

- package-lock.json
- package.json
- src/components/FormRating.jsx
- src/components/StarRating.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
- src/services/modules.js
> [main-group-22][requisito 11]

- src/components/Main.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetails.jsx
- src/components/ShopCart.jsx
- src/components/ShoppingCartCard.css
- src/components/ShoppingCartCard.jsx
> [Grupo 12] Requisito 15

- src/App.js
- src/components/Categories.jsx
- src/components/ProductList.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
- src/services/api.js
> [Group 19] [requisito 07 fix]

- src/App.css
- src/App.js
- src/components/ListCategories.jsx
- src/components/ListProducts.jsx
- src/components/SearchBox.jsx
- src/components/pages/Home.jsx
- src/components/pages/ItemProduct.jsx
- src/services/api.js
Fiz uma nova página na pasta pages, que representa os detalhes de um produto quando clicado nele em ListProducts
> Requisito 07

- src/App.js
- src/components/CartItem.jsx
- src/components/DetailsPage.jsx
- src/components/PageCart.jsx
Refatorado toda a funcionalidade ao redor do estado cart e criado um controle de quantidade de items.
> Grupo 10/req 10

- src/App.js
- src/components/Categories.jsx
- src/components/Input.jsx
- src/services/api.js
> inicio da implementaçao da seleçao de categorias

- src/App.js
- src/Components/CardList.js
- src/Components/Info.js
- src/Components/ShoppingCart.js
- src/services/api.js
> [Grupo 5]Requirimento 7

- src/components/ProductCard.jsx
- src/pages/Cart.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
- src/services/modules.js
> [main-group-22][requisito 13]

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/components/CartButton.jsx
- src/components/Categories.jsx
- src/pages/Cart.jsx
> Main group req fix

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/components/CartButton.jsx
- src/components/Categories.jsx
[x] Adicionei css e cart icon button
> Main group req x

- src/App.js
- src/components/ProductCard.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
Correção dos requisitos 08 e 09
> [Requisitos 08 e 09 ajustados]

- src/services/dataLocalStorage.js
Funções implementadas:
- addLocalStorage(key, value);
-->O importante a se frisar sobre essa função é que ela sempre salva seus valores dentro de um array. O que significa que a função getLocalStorage() ira sempre retornar uma coleção de objeto ou valores dentro de um array.
- getLocalStorage(key);
-->retornar uma coleção de objeto ou valores dentro de um array.
- updateLocalStorage(key, value);
-->Essa função sobrescreve  todo o value no localstorage.
- removeLocalStorage(key);
-->Essa função remove um item especifico dentro do localstorage.
- clearLocalStorage();
-->essa função limpa todo o LocalStorage;
> Main group 16 criação do localsorage

- src/components/Card.js
- src/components/Home.js
- src/components/ShoppingCart.js
> [Grupo 7][Req 10]

- src/App.js
- src/__tests__/requirement08.test.js
- src/components/CategoryList.jsx
- src/components/SearchBar.jsx
- src/components/SearchList.jsx
- src/pages/Index.jsx
- src/pages/ShoppingCart.jsx
> [GRUPO 8][Requisito 8]

- src/App.js
- src/components/ProductCard.jsx
- src/pages/Details.jsx
- src/pages/Home.jsx
Requisito 7 Completo, com a ajuda de todo o grupo e mais o Luanderson e o Edu!
> Main group 11 requisito 7

- src/pages/Details.jsx
Requisito 9 completo colocando o compoente do botão criando no requisto 8 na página de detalhes criada no requisito 7.
> Main group 11 requisito 9

- src/components/DetailsCard.js
- src/components/Home.js
> [Grupo 7][Req 1 a 10]

- src/App.js
- src/components/AllProducts.jsx
- src/components/Home.jsx
- src/components/Loading.jsx
- src/components/Search.jsx
- src/services/api.js
- src/services/api2.js
> Group 18 requisito 5

- src/App.js
- src/__tests__/requirement09.test.js
- src/components/ButtonSendCart.jsx
- src/components/SearchList.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
9. Adicione um produto ao carrinho a partir de sua tela de exibição detalhada
> [GRUPO 8][REQUISITO 9]

- package-lock.json
- src/components/Avaliacao.js
- src/components/Detail.js
> [Grupo 3] [Requisito 11]

- src/components/Header.jsx
- src/components/Search.jsx
> Main group 18 requisito3

- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/pages/ProductDetails.jsx
> [Group 19] [requisito 11]

- src/Assets/data.js
- src/components/Checkout.jsx
Atualização na forma que é listada a lista de estados para cadastro
Criei a pasta Assets para futura utilização de itens e materiais para a personalização da página
> atualizando lista selected de estados

- src/components/Detail.js
> [GRUPO 3] Requisitos 9 e 11

- src/App.js
- src/components/ProductCard.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
Adicionei os botões, porém estão associados ao state.
> [Grupo 19] Requisito 10 incompleto

- src/App.js
- src/Components/CardList.js
- src/Components/Checkout.js
- src/Components/Info.js
- [x ] Aprovados no projeto.... check kkkkk :rocket: 
VQV GALERAAAAA! FRUTO DA NOSSA COLABORAÇÃO E APRENDIZADO EM CONJUNTO :laughing: :heart:
> [Grupo 5] Requisito10 - Finalizado :rocket: 

- src/App.css
- src/components/MyForm.jsx
- src/pages/Details.jsx
Requisito 11, primeira parte concluída, falta fazer as estrelinhas e o mais e menos para adicionar ao carrinho!
> Main group 11 requisito11

- src/App.css
- src/components/AddToCart.jsx
- src/components/CartItems.jsx
- src/components/ItemCard.jsx
- src/components/ProductCard.jsx
Requisito 10 completo passsando nos testes, faltando implementar o botão de remover que não é exigido para passar.
> Main group 11 requisito 10

- src/components/DetailsCard.js
- src/components/Home.js
- src/components/Rating.js
Basicamente fiz o requerimento 11 passar, falta criar a função handleChange, alguma função para lidar com o submmit e algumas função para lidar com Local Storage
> [Group 7][Req 11]

- src/App.js
- src/components/ProductDetails.js
- src/components/ProductList.js
- src/components/ShoppingCart.js
Resolvi o requisito 9, e a questão das quantidades no carrinho foram corrigidas nesse PR
> [requisito 9] funcionando

- public/index.html
- src/App.css
- src/components/EvaluationArea.jsx
- src/components/pages/ItemProduct.jsx
> Requesito 11 completo version 1.0

- src/components/CartItem.jsx
- src/components/ProductCart.jsx
- src/pages/Checkout.jsx
> [GRUPO 6[ [REQ 8]

- src/components/ProductCart.jsx
- src/components/ProductList.jsx
- src/pages/ProductDetails.jsx
Adicionando um parágrafo de frete grátis no productCard e no ProductDetails caso o item tenha o frete gratis.
> [Grupo 6][Requisito 15]

- src/services/dataLocalStorage.js
atualização das funções para add e atualizar lista de compra
> atualização do arquivo dataLocalstorage

- src/components/ItemCard.jsx
> Group-11-Requisito-14-Completo

- .stylelintignore
- src/__tests__/requirement11.test.js
- src/components/Coments.jsx
- src/components/Rating.jsx
- src/pages/ProductDetails.jsx
- src/styles/rating.css
Commit inicial do requisito 11
> [GRUPO 8][REQUISITO 11]

- src/App.js
- src/components/ProductsList.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
> [Main group 21] Details add cart

- src/pages/ProductDetails.jsx
Add botão de add ao carrinho de compras.
> Main group 16 requisito 9

- src/components/Home/CartListProduct.jsx
- src/pages/ProductDetails.jsx
- src/services/dataLocalStorage.js
> [Grupo 16] Requisito8

- src/App.css
- src/App.js
- src/components/AddToCart.jsx
- src/components/CartItems.jsx
- src/components/CheckoutForm.jsx
- src/components/ItemCard.jsx
- src/pages/Checkout.jsx
Requisito 12 concluído, faltando só alguns ajustes adicionais (funcionalidade do botão comprar e validar formulário)  e mudanças no css
> Grupo-11-Requisito-12-Completo

- src/components/ProductCard.jsx
- src/pages/Details.jsx
Boa noite pessoal.  Aqui está o que já temos do Requisito 15.
> Main group 11 requisito 15

- src/App.js
- src/components/Card.js
- src/components/Checkout.js
- src/components/DetailsCard.js
- src/components/Home.js
- src/components/InfoBuyer.js
- src/components/InputBuy.js
- src/components/PaymentMethod.js
- src/components/Rating.js
- src/components/ReviewProducts.js
- src/components/ShoppingCart.js
- src/components/ShoppingCartFinal.js
> [Group 7] [REQ 12]

- src/components/SearchBar.jsx
- src/pages/ProductDetails.jsx
Comecei meus commits com o botão, vou deixar já pelo menos ele no código porque eu sei que vou precisar dele, meu problema tá sendo a função que vai fazer ele funcionar. Não tô conseguindo criar essa função.
> Main group 01 feature 09

- src/App.js
- src/components/DetailsCard.js
- src/components/Home.js
- src/components/ShoppingCart.js
> [Main group 7][Req 13]  

- .vscode/launch.json
- src/components/CardProduct.js
- src/components/Cart.js
- src/components/Detail.js
- src/components/Home.js
- src/components/ItemProductCart.js
Requisitos 10 e 11 finalizados
> [GRUPO 3] [Requisitos 10 e 11]

- src/components/ProductCard.jsx
- src/components/Star.jsx
- src/pages/Checkout.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
- src/services/api.js
**Mudanças**
**Added:** _LocalStorage_ em todas páginas da aplicação e  _Botão para limpar_ todos os produtos do carrinho de compras
**Fix:** Ajustado funções normais para Arrow Functions
> [GRUPO 23] LOCALSTORAGE

- src/App.css
- src/components/AddToCart.jsx
- src/components/CartItems.jsx
- src/components/ItemCard.jsx
- src/components/ProductCard.jsx
- src/pages/Details.jsx
Adiciona funcionalidade nos botões de somar e retirar quantidade da página Details
Adiciona Frete Grátis à pagina de details
> Requisito 15 - Completo

- src/App.js
- src/components/ElementsHome.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/index.css
- src/pages/Checkout.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
Pessoal nesse PR eu ajustei um Bugzinho que estava aparecendo no LocalStorage e coloquei um mínimo de CSS na nossa aplicação somente para facilitar nossa visualização.
> [GRUPO 23] MINIMO CSS / FIX BUGS

- src/components/ProductCard.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
O clickCart do itemDetails foi atualizado e tentei implementar a 9 também, mas continua assíncrona e utilizando o "getItemById". no componentDidMount
> REQUEST 10 V3
